### superadmin - addAdmin  // Додавати
POST http://localhost:8080/api/superadmin/admin
Content-Type: application/json
Accept: application/json

{
  "firstName": "admin",
  "lastName": "admin",
  "email": "admin@gmail.com",
  "password":"123",
  "balance": 100.00
}

### superadmin - deleteAdmin  // видаляти адмінів
DELETE http://localhost:8080/api/superadmin/admin/4

### superadmin - assignAdmin  // призначати нових
PUT http://localhost:8080/api/superadmin/admin/1


### admin - addUser   // може створювати
POST http://localhost:8080/api/admin/user
Content-Type: application/json
Accept: application/json

{
  "firstName": "Andrey",
  "lastName": "Andreev",
  "email": "andrey@gmail.com",
  "password":"123",
  "balance": 1000.00
}

### admin - blockUser   //блокує
PUT http://localhost:8080/api/admin/user
//impl

### admin - deleteUser  // Додавати продукти
DELETE http://localhost:8080/api/admin/user/6


### admin - addProduct
POST http://localhost:8080/api/admin/product
Content-Type: application/json
Accept: application/json

{
  "name": "tea",
  "price": 5.00
}

### admin - deleteProduct  //видаляти продукти
DELETE http://localhost:8080/api/admin/product/4

### admin - editProduct // оновлювати інфо про продукти
PUT http://localhost:8080/api/admin/product
Content-Type: application/json
Accept: application/json

{
  "productId": "4",
  "name": "cheese",
  "price": 70.0
}

### user - addOrder // Додати продукт в заказ
POST http://localhost:8080/api/user/order
Content-Type: application/json
Accept: application/json

{
  "userId": 7,
  "products": {
    "1": 2,
    "2": 1
  }
}

### user - removeProductToOrder // видалити продукт з заказа
DELETE http://localhost:8080/api/user/order
Content-Type: application/json
Accept: application/json

{
  "userId": 1,
  "orderId": 1,
  "products": {
    "1": 1
  }
}

### user - findAllOrdersByUserId  // переглянути список ордерів у юзера
GET http://localhost:8080/api/user/orders/1
Content-Type: application/json
Accept: application/json

###  user - findById  // переглянути конкретний ордер
GET http://localhost:8080/api/user/order/8
Content-Type: application/json
Accept: application/json

//impl
###  user - registerUser   // Реєстрація
POST http://localhost:8080/api/user/register
Content-Type: application/json
Accept: application/json


###  user - editProfile // Оновити особистий профіль
PUT http://localhost:8080/api/user/profile
Content-Type: application/json
Accept: application/json

{
  "userId": 1,
  "firstName": "Ivan2",
  "lastName": "Ivanov2",
  "email": "ivanov@gmail.com",
  "password": "123",
  "balance": 800
}

###  add - balance  // додати кошти на баланс
PUT http://localhost:8080/api/user/balance
Content-Type: application/json
Accept: application/json

{
  "userId": 7,
  "balance": 2000
}




